name: Sarmishsoy Water Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '0 3 * * *'   # UTC 03:00 = O'zbekiston 08:00 (ish boshlanganda)
  - cron: '0 21 * * *'  # UTC 21:00 = O'zbekiston 02:00 (tunda)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          MIJOZ_BOT_TOKEN: ${{ secrets.MIJOZ_BOT_TOKEN }}
          ADMIN_BOT_TOKEN: ${{ secrets.ADMIN_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BAKLASHKA_GROUP_ID: ${{ secrets.BAKLASHKA_GROUP_ID }}
          LITR_GROUP_ID: ${{ secrets.LITR_GROUP_ID }}
          WORK_START: ${{ secrets.WORK_START }}
          WORK_END: ${{ secrets.WORK_END }}
        run: |
          cd bot
          python main.py